apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
          # envFrom:
          #   - secretRef:
          #       name: environment-variables
          env:
            - name: VITE_NENKYUU_CALENDAR_API_URL
              value: https://leaves-api.jtektrnd.net
            - name: VITE_GROUP_MANAGER_API_URL
              value: https://groups-api.jtektrnd.net
            - name: VITE_USER_MANAGER_API_URL
              value: https://employees-api.jtektrnd.net
            - name: VITE_LOGIN_URL
              value: https://employees-api.jtektrnd.net/v3/auth/login
            - name: VITE_AUTH_IDENTIFICATION_URL
              value: https://employees-api.jtektrnd.net/v3/users/self
            - name: VITE_APPS_URL
              value: https://apps.jtektrnd.net
            - name: VITE_MINIMUM_LEAVES
              value: "5"
            - name: VITE_LEAVE_TYPES_FULL_DAY
              value: 有休
            - name: VITE_LEAVE_TYPES_MORNING
              value: 前半休
            - name: VITE_LEAVE_TYPES_AFTERNOON
              value: 後半休
            - name: VITE_LEAVE_TYPES_EXCLUDED
              value: 振休
            - name: VITE_AUTH_ENRICHMENT_ID_FIELD
              value: _id
            - name: VITE_OIDC_AUTHORITY
              value: https://keycloak.jtektrnd.net/realms/jtekt
            - name: VITE_OIDC_CLIENT_ID
              value: public
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  ports:
    - port: 80
  selector:
    app: ${APPLICATION_NAME}
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: 年休カレンダー
    gethomepage.dev/icon: https://gitlab.jtektrnd.net/uploads/-/system/project/avatar/328/calendar-beach-rounded-bg.png
    gethomepage.dev/group: 業務アプリ
    gethomepage.dev/pod-selector: app=annual-leave-calendar-gui
spec:
  rules:
    - host: leaves.jtektrnd.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${APPLICATION_NAME}
                port:
                  number: 80
